triggers:
- name: composer-cicd-pre-merge
  description: Trigger to verify dag integity on a PR
  tags: demo
  disabled: false
  filename: cloudbuild/pre-merge.yaml
  include_build_logs: INCLUDE_BUILD_LOGS_WITH_STATUS
  github:
    owner: samm40me
    name: composer_cicd
    pull_request:
      branch: ^(main|test|uat|preprod)$
      comment_control: COMMENTS_DISABLED
      invert_regex: false
- name: composer-cicd-on-merge
  description: Trigger to Deploy Dags
  tags: demo
  disabled: false
  filename: cloudbuild/on-merge.yaml
  github:
    owner: samm40me
    name: composer_cicd
    push:
      branch: ^(main|test|uat|preprod)$
      invert_regex: false
